### ISSUE TITLE
Tradução [pt-br]: 04 - String variables

### ISSUE THREAD

**Issue by cyz** [cyz/c9-python-getting-started#3]
Precisamos traduzir o conteúdo da [pasta indicada no título da issue](https://github.com/cyz/c9-python-getting-started/tree/master/python-for-beginners) + arquivo de [power point](https://github.com/cyz/c9-python-getting-started/tree/master/python-for-beginners/Slides) relacionado a aula.

**Comment by jjeanjacques10** [comment]
Vou realizar a tradução do Módulo 04 - String variables.
